/* ================================================================
   The Constitution of the United States — Full Text
   ----------------------------------------------------------------
   A U.S. government edict work: not subject to copyright. Text
   verified against the National Archives official transcriptions
   (archives.gov/founding-docs), which preserve original spelling
   and punctuation ("chuse," "controul," "encreased," etc. — not
   typos). Structured by Article/Section and Amendment for lookup,
   same pattern as the UCC section of this site.
   ================================================================ */

const CONSTITUTION_SECTIONS = [
  { code: "Preamble", part: "Preamble", title: "Preamble", def: "We the People of the United States, in Order to form a more perfect Union, establish Justice, insure domestic Tranquility, provide for the common defence, promote the general Welfare, and secure the Blessings of Liberty to ourselves and our Posterity, do ordain and establish this Constitution for the United States of America." },

  { code: "Art. I, §1", part: "Article I", title: "Legislative Power Vested in Congress", def: "All legislative Powers herein granted shall be vested in a Congress of the United States, which shall consist of a Senate and House of Representatives." },
  { code: "Art. I, §2", part: "Article I", title: "The House of Representatives", def: "The House of Representatives shall be composed of Members chosen every second Year by the People of the several States... No Person shall be a Representative who shall not have attained to the Age of twenty five Years, and been seven Years a Citizen of the United States, and who shall not, when elected, be an Inhabitant of that State in which he shall be chosen. The House of Representatives shall chuse their Speaker and other Officers; and shall have the sole Power of Impeachment." },
  { code: "Art. I, §3", part: "Article I", title: "The Senate", def: "The Senate of the United States shall be composed of two Senators from each State... for six Years; and each Senator shall have one Vote. No Person shall be a Senator who shall not have attained to the Age of thirty Years, and been nine Years a Citizen of the United States... The Vice President of the United States shall be President of the Senate, but shall have no Vote, unless they be equally divided. The Senate shall have the sole Power to try all Impeachments." },
  { code: "Art. I, §4", part: "Article I", title: "Elections of Senators and Representatives", def: "The Times, Places and Manner of holding Elections for Senators and Representatives, shall be prescribed in each State by the Legislature thereof; but the Congress may at any time by Law make or alter such Regulations, except as to the Places of chusing Senators. The Congress shall assemble at least once in every Year." },
  { code: "Art. I, §5", part: "Article I", title: "Rules of Proceedings", def: "Each House shall be the Judge of the Elections, Returns and Qualifications of its own Members, and a Majority of each shall constitute a Quorum to do Business. Each House may determine the Rules of its Proceedings, punish its Members for disorderly Behaviour, and, with the Concurrence of two thirds, expel a Member." },
  { code: "Art. I, §6", part: "Article I", title: "Compensation, Privileges, Disabilities of Members", def: "The Senators and Representatives shall receive a Compensation for their Services... They shall in all Cases, except Treason, Felony and Breach of the Peace, be privileged from Arrest during their Attendance at the Session of their respective Houses... and for any Speech or Debate in either House, they shall not be questioned in any other Place." },
  { code: "Art. I, §7", part: "Article I", title: "Legislative Process (the Veto)", def: "All Bills for raising Revenue shall originate in the House of Representatives; but the Senate may propose or concur with Amendments as on other Bills. Every Bill which shall have passed the House of Representatives and the Senate, shall, before it become a Law, be presented to the President of the United States; If he approve he shall sign it, but if not he shall return it, with his Objections... If after such Reconsideration two thirds of that House shall agree to pass the Bill, it shall be sent, together with the Objections, to the other House... and if approved by two thirds of that House, it shall become a Law." },
  { code: "Art. I, §8", part: "Article I", title: "Powers of Congress", def: "The Congress shall have Power To lay and collect Taxes, Duties, Imposts and Excises, to pay the Debts and provide for the common Defence and general Welfare of the United States... To borrow Money on the credit of the United States; To regulate Commerce with foreign Nations, and among the several States, and with the Indian Tribes; To coin Money... To declare War... To raise and support Armies... To provide and maintain a Navy... and To make all Laws which shall be necessary and proper for carrying into Execution the foregoing Powers." },
  { code: "Art. I, §9", part: "Article I", title: "Powers Denied Congress", def: "The Privilege of the Writ of Habeas Corpus shall not be suspended, unless when in Cases of Rebellion or Invasion the public Safety may require it. No Bill of Attainder or ex post facto Law shall be passed. No Title of Nobility shall be granted by the United States." },
  { code: "Art. I, §10", part: "Article I", title: "Powers Denied the States", def: "No State shall enter into any Treaty, Alliance, or Confederation; grant Letters of Marque and Reprisal; coin Money; emit Bills of Credit; make any Thing but gold and silver Coin a Tender in Payment of Debts; pass any Bill of Attainder, ex post facto Law, or Law impairing the Obligation of Contracts, or grant any Title of Nobility." },

  { code: "Art. II, §1", part: "Article II", title: "The Executive Power; Election of the President", def: "The executive Power shall be vested in a President of the United States of America. He shall hold his Office during the Term of four Years... No Person except a natural born Citizen, or a Citizen of the United States, at the time of the Adoption of this Constitution, shall be eligible to the Office of President; neither shall any Person be eligible to that Office who shall not have attained to the Age of thirty five Years, and been fourteen Years a Resident within the United States." },
  { code: "Art. II, §2", part: "Article II", title: "Powers of the President", def: "The President shall be Commander in Chief of the Army and Navy of the United States... he shall have Power to grant Reprieves and Pardons for Offences against the United States, except in Cases of Impeachment. He shall have Power, by and with the Advice and Consent of the Senate, to make Treaties... and he shall nominate, and by and with the Advice and Consent of the Senate, shall appoint Ambassadors... Judges of the supreme Court, and all other Officers of the United States." },
  { code: "Art. II, §3", part: "Article II", title: "Duties of the President", def: "He shall from time to time give to the Congress Information of the State of the Union, and recommend to their Consideration such Measures as he shall judge necessary and expedient... he shall take Care that the Laws be faithfully executed, and shall Commission all the Officers of the United States." },
  { code: "Art. II, §4", part: "Article II", title: "Impeachment", def: "The President, Vice President and all civil Officers of the United States, shall be removed from Office on Impeachment for, and Conviction of, Treason, Bribery, or other high Crimes and Misdemeanors." },

  { code: "Art. III, §1", part: "Article III", title: "Judicial Power; Tenure of Judges", def: "The judicial Power of the United States, shall be vested in one supreme Court, and in such inferior Courts as the Congress may from time to time ordain and establish. The Judges, both of the supreme and inferior Courts, shall hold their Offices during good Behaviour, and shall, at stated Times, receive for their Services, a Compensation, which shall not be diminished during their Continuance in Office." },
  { code: "Art. III, §2", part: "Article III", title: "Jurisdiction of Federal Courts", def: "The judicial Power shall extend to all Cases, in Law and Equity, arising under this Constitution, the Laws of the United States, and Treaties made... The Trial of all Crimes, except in Cases of Impeachment, shall be by Jury; and such Trial shall be held in the State where the said Crimes shall have been committed." },
  { code: "Art. III, §3", part: "Article III", title: "Treason", def: "Treason against the United States, shall consist only in levying War against them, or in adhering to their Enemies, giving them Aid and Comfort. No Person shall be convicted of Treason unless on the Testimony of two Witnesses to the same overt Act, or on Confession in open Court." },

  { code: "Art. IV, §1", part: "Article IV", title: "Full Faith and Credit", def: "Full Faith and Credit shall be given in each State to the public Acts, Records, and judicial Proceedings of every other State." },
  { code: "Art. IV, §2", part: "Article IV", title: "Privileges and Immunities; Extradition", def: "The Citizens of each State shall be entitled to all Privileges and Immunities of Citizens in the several States. A Person charged in any State with Treason, Felony, or other Crime, who shall flee from Justice, and be found in another State, shall on Demand of the executive Authority of the State from which he fled, be delivered up, to be removed to the State having Jurisdiction of the Crime." },
  { code: "Art. IV, §3", part: "Article IV", title: "New States; Federal Property", def: "New States may be admitted by the Congress into this Union; but no new State shall be formed or erected within the Jurisdiction of any other State... without the Consent of the Legislatures of the States concerned as well as of the Congress." },
  { code: "Art. IV, §4", part: "Article IV", title: "Guarantee of Republican Government", def: "The United States shall guarantee to every State in this Union a Republican Form of Government, and shall protect each of them against Invasion; and on Application of the Legislature, or of the Executive... against domestic Violence." },

  { code: "Art. V", part: "Article V", title: "Amendment Process", def: "The Congress, whenever two thirds of both Houses shall deem it necessary, shall propose Amendments to this Constitution, or, on the Application of the Legislatures of two thirds of the several States, shall call a Convention for proposing Amendments, which, in either Case, shall be valid to all Intents and Purposes, as Part of this Constitution, when ratified by the Legislatures of three fourths of the several States, or by Conventions in three fourths thereof." },

  { code: "Art. VI", part: "Article VI", title: "Supremacy Clause; Oaths of Office", def: "This Constitution, and the Laws of the United States which shall be made in Pursuance thereof; and all Treaties made, or which shall be made, under the Authority of the United States, shall be the supreme Law of the Land; and the Judges in every State shall be bound thereby, any Thing in the Constitution or Laws of any State to the Contrary notwithstanding... but no religious Test shall ever be required as a Qualification to any Office or public Trust under the United States." },

  { code: "Art. VII", part: "Article VII", title: "Ratification", def: "The Ratification of the Conventions of nine States, shall be sufficient for the Establishment of this Constitution between the States so ratifying the Same. Done in Convention by the Unanimous Consent of the States present the Seventeenth Day of September in the Year of our Lord one thousand seven hundred and Eighty seven." },

  // ---------------- BILL OF RIGHTS (Amendments I–X, ratified Dec. 15, 1791) ----------------
  { code: "Amend. I", part: "Bill of Rights", title: "Freedom of Religion, Speech, Press, Assembly, Petition", def: "Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances." },
  { code: "Amend. II", part: "Bill of Rights", title: "Right to Bear Arms", def: "A well regulated Militia, being necessary to the security of a free State, the right of the people to keep and bear Arms, shall not be infringed." },
  { code: "Amend. III", part: "Bill of Rights", title: "Quartering of Soldiers", def: "No Soldier shall, in time of peace be quartered in any house, without the consent of the Owner, nor in time of war, but in a manner to be prescribed by law." },
  { code: "Amend. IV", part: "Bill of Rights", title: "Search and Seizure", def: "The right of the people to be secure in their persons, houses, papers, and effects, against unreasonable searches and seizures, shall not be violated, and no Warrants shall issue, but upon probable cause, supported by Oath or affirmation, and particularly describing the place to be searched, and the persons or things to be seized." },
  { code: "Amend. V", part: "Bill of Rights", title: "Grand Jury, Double Jeopardy, Self-Incrimination, Due Process, Takings", def: "No person shall be held to answer for a capital, or otherwise infamous crime, unless on a presentment or indictment of a Grand Jury... nor shall any person be subject for the same offence to be twice put in jeopardy of life or limb; nor shall be compelled in any criminal case to be a witness against himself, nor be deprived of life, liberty, or property, without due process of law; nor shall private property be taken for public use, without just compensation." },
  { code: "Amend. VI", part: "Bill of Rights", title: "Right to a Speedy, Public Trial by Jury; Right to Counsel", def: "In all criminal prosecutions, the accused shall enjoy the right to a speedy and public trial, by an impartial jury of the State and district wherein the crime shall have been committed... and to be informed of the nature and cause of the accusation; to be confronted with the witnesses against him; to have compulsory process for obtaining witnesses in his favor, and to have the Assistance of Counsel for his defence." },
  { code: "Amend. VII", part: "Bill of Rights", title: "Right to Jury Trial in Civil Cases", def: "In Suits at common law, where the value in controversy shall exceed twenty dollars, the right of trial by jury shall be preserved, and no fact tried by a jury, shall be otherwise re-examined in any Court of the United States, than according to the rules of the common law." },
  { code: "Amend. VIII", part: "Bill of Rights", title: "Excessive Bail, Fines, and Cruel Punishment", def: "Excessive bail shall not be required, nor excessive fines imposed, nor cruel and unusual punishments inflicted." },
  { code: "Amend. IX", part: "Bill of Rights", title: "Unenumerated Rights Retained by the People", def: "The enumeration in the Constitution, of certain rights, shall not be construed to deny or disparage others retained by the people." },
  { code: "Amend. X", part: "Bill of Rights", title: "Powers Reserved to the States", def: "The powers not delegated to the United States by the Constitution, nor prohibited by it to the States, are reserved to the States respectively, or to the people." },

  // ---------------- LATER AMENDMENTS (XI–XXVII) ----------------
  { code: "Amend. XI", part: "Later Amendments", title: "Suits Against States (1795)", def: "The Judicial power of the United States shall not be construed to extend to any suit in law or equity, commenced or prosecuted against one of the United States by Citizens of another State, or by Citizens or Subjects of any Foreign State." },
  { code: "Amend. XII", part: "Later Amendments", title: "Election of President and Vice President (1804)", def: "The Electors shall meet in their respective states and vote by ballot for President and Vice-President, one of whom, at least, shall not be an inhabitant of the same state with themselves... The person having the greatest number of votes for President, shall be the President, if such number be a majority of the whole number of Electors appointed." },
  { code: "Amend. XIII", part: "Later Amendments", title: "Abolition of Slavery (1865)", def: "Neither slavery nor involuntary servitude, except as a punishment for crime whereof the party shall have been duly convicted, shall exist within the United States, or any place subject to their jurisdiction." },
  { code: "Amend. XIV", part: "Later Amendments", title: "Citizenship, Due Process, Equal Protection (1868)", def: "All persons born or naturalized in the United States, and subject to the jurisdiction thereof, are citizens of the United States and of the State wherein they reside. No State shall make or enforce any law which shall abridge the privileges or immunities of citizens of the United States; nor shall any State deprive any person of life, liberty, or property, without due process of law; nor deny to any person within its jurisdiction the equal protection of the laws." },
  { code: "Amend. XV", part: "Later Amendments", title: "Right to Vote Regardless of Race (1870)", def: "The right of citizens of the United States to vote shall not be denied or abridged by the United States or by any State on account of race, color, or previous condition of servitude." },
  { code: "Amend. XVI", part: "Later Amendments", title: "Federal Income Tax (1913)", def: "The Congress shall have power to lay and collect taxes on incomes, from whatever source derived, without apportionment among the several States, and without regard to any census or enumeration." },
  { code: "Amend. XVII", part: "Later Amendments", title: "Direct Election of Senators (1913)", def: "The Senate of the United States shall be composed of two Senators from each State, elected by the people thereof, for six years; and each Senator shall have one vote." },
  { code: "Amend. XVIII", part: "Later Amendments", title: "Prohibition of Alcohol (1919, repealed 1933)", def: "After one year from the ratification of this article the manufacture, sale, or transportation of intoxicating liquors within, the importation thereof into, or the exportation thereof from the United States and all territory subject to the jurisdiction thereof for beverage purposes is hereby prohibited. Repealed by the 21st Amendment." },
  { code: "Amend. XIX", part: "Later Amendments", title: "Women's Suffrage (1920)", def: "The right of citizens of the United States to vote shall not be denied or abridged by the United States or by any State on account of sex." },
  { code: "Amend. XX", part: "Later Amendments", title: "Terms of the President, Congress; \"Lame Duck\" (1933)", def: "The terms of the President and Vice President shall end at noon on the 20th day of January, and the terms of Senators and Representatives at noon on the 3d day of January, of the years in which such terms would have ended if this article had not been ratified." },
  { code: "Amend. XXI", part: "Later Amendments", title: "Repeal of Prohibition (1933)", def: "The eighteenth article of amendment to the Constitution of the United States is hereby repealed." },
  { code: "Amend. XXII", part: "Later Amendments", title: "Presidential Term Limits (1951)", def: "No person shall be elected to the office of the President more than twice, and no person who has held the office of President, or acted as President, for more than two years of a term to which some other person was elected President shall be elected to the office of the President more than once." },
  { code: "Amend. XXIII", part: "Later Amendments", title: "Electoral Votes for Washington, D.C. (1961)", def: "The District constituting the seat of Government of the United States shall appoint... a number of electors of President and Vice President equal to the whole number of Senators and Representatives in Congress to which the District would be entitled if it were a State, but in no event more than the least populous State." },
  { code: "Amend. XXIV", part: "Later Amendments", title: "Abolition of Poll Taxes (1964)", def: "The right of citizens of the United States to vote in any primary or other election for President or Vice President... shall not be denied or abridged by the United States or any State by reason of failure to pay any poll tax or other tax." },
  { code: "Amend. XXV", part: "Later Amendments", title: "Presidential Succession and Disability (1967)", def: "In case of the removal of the President from office or of his death or resignation, the Vice President shall become President. Whenever there is a vacancy in the office of the Vice President, the President shall nominate a Vice President who shall take office upon confirmation by a majority vote of both Houses of Congress." },
  { code: "Amend. XXVI", part: "Later Amendments", title: "Voting Age Set to 18 (1971)", def: "The right of citizens of the United States, who are eighteen years of age or older, to vote shall not be denied or abridged by the United States or by any State on account of age." },
  { code: "Amend. XXVII", part: "Later Amendments", title: "Congressional Pay Raises (Ratified 1992)", def: "No law, varying the compensation for the services of the Senators and Representatives, shall take effect, until an election of Representatives shall have intervened. First proposed in 1789 alongside the Bill of Rights; not ratified until 203 years later." },
];
