/* ================================================================
   Black's Law Dictionary, 2nd Edition (1910) by Henry Campbell
   Black — public domain. This is the newest edition of Black's
   Law Dictionary that is legally free to use; the 3rd edition
   (1933) onward, and all modern editions, remain copyrighted by
   Thomson Reuters/West.

   This is a curated set of ~140 core, high-use legal terms hand-
   verified against the 1910 text (avoids OCR artifacts from the
   scanned original). For the complete ~12,900-entry text, the
   only public full-text source is the raw OCR scan on archive.org
   (archive.org/details/blacks-law-dictionary-2nd-edition-1910),
   which needs cleanup before it's usable as structured data —
   see the note at the bottom of this file for a parsing approach.
   ================================================================ */

const BLACKS_LAW_1910 = [
  { word: "ABANDONMENT", pos: "n.", def: "The surrender, relinquishment, disclaimer, or cession of property or of rights. The giving up of a thing absolutely, without reference to any particular person or purpose." },
  { word: "ABATEMENT", pos: "n.", def: "The act of abating, or the state of being abated; a diminution, decrease, or reduction; suspension or defeat, as in the case of a lawsuit." },
  { word: "ABROGATE", pos: "v.", def: "To annul, repeal, or abolish; to make void by a subsequent act; said of the repeal or annulling of a former law by an act of the legislative power." },
  { word: "ACQUITTAL", pos: "n.", def: "The legal and formal certification of the innocence of a person who has been charged with crime; a deliverance or setting free from the charge of an offense, by verdict of a jury or otherwise." },
  { word: "AD LITEM", pos: "Lat.", def: "For the suit; pending the suit; during the litigation. A guardian ad litem is a guardian appointed to prosecute or defend a suit on behalf of a party incapacitated by infancy or otherwise." },
  { word: "AFFIDAVIT", pos: "n.", def: "A statement or declaration reduced to writing, and sworn or affirmed to before some officer who has authority to administer an oath." },
  { word: "AGGRIEVED PARTY", pos: "n.", def: "One whose legal right is invaded by an act complained of, or whose pecuniary interest is directly and adversely affected by a decree or judgment." },
  { word: "BAILMENT", pos: "n.", def: "A delivery of goods or personal property, by one person to another, in trust for the execution of a special object upon or in relation to such goods, and upon a contract, express or implied, to conform to the object or purpose of the trust." },
  { word: "BONA FIDE", pos: "Lat.", def: "In or with good faith; honestly, openly, and sincerely; without deceit or fraud." },
  { word: "BREACH OF CONTRACT", pos: "n.", def: "The failure, without legal excuse, to perform any promise which forms the whole or part of a contract." },
  { word: "CAVEAT EMPTOR", pos: "Lat.", def: "Let the buyer beware. This maxim summarizes the rule that a purchaser must examine, judge, and test for himself." },
  { word: "CERTIORARI", pos: "n.", def: "The name of a writ issued by a superior court, directed to an inferior court, requiring the latter to send the record of a cause pending before it." },
  { word: "CONSIDERATION", pos: "n.", def: "The inducement to a contract. The cause, motive, price, or impelling influence which induces a contracting party to enter into a contract." },
  { word: "CONTRACT", pos: "n.", def: "An agreement between two or more persons which creates an obligation to do or not to do a particular thing." },
  { word: "DAMAGES", pos: "n.", def: "A pecuniary compensation or indemnity, which may be recovered in the courts by any person who has suffered loss, detriment, or injury, through the unlawful act or negligence of another." },
  { word: "DE FACTO", pos: "Lat.", def: "In fact, in deed, actually. This phrase is used to characterize an officer, a government, a past action, or a state of affairs which must be accepted for all practical purposes, but is illegal or illegitimate." },
  { word: "DE JURE", pos: "Lat.", def: "Of right; legitimate; lawful; by right and just title. In this sense it is the contrary of de facto." },
  { word: "DEMURRER", pos: "n.", def: "In common law pleading, a pleading which admits the facts as alleged by the opposing party, but denies that they are sufficient to sustain the claim or defense." },
  { word: "DUE PROCESS OF LAW", pos: "n.", def: "Law in its regular course of administration through courts of justice. A course of legal proceedings according to those rules and principles which have been established for the enforcement and protection of private rights." },
  { word: "EASEMENT", pos: "n.", def: "A liberty, privilege, or advantage in land, without profit, existing distinct from the ownership of the soil; a right which one proprietor has to some profit, benefit, or beneficial use out of the estate of another proprietor." },
  { word: "ESTOPPEL", pos: "n.", def: "A bar or impediment raised by the law, which precludes a man from alleging or from denying a certain fact or state of facts, in consequence of his own previous act, allegation, or denial of a contrary tenor." },
  { word: "EX PARTE", pos: "Lat.", def: "On the one side only; by or for one party; done for, in behalf of, or on the application of, one party only." },
  { word: "FELONY", pos: "n.", def: "At common law, an offense occasioning a total forfeiture of either lands or goods, to which capital or other punishment might be superadded, according to the degree of guilt." },
  { word: "FIDUCIARY", pos: "a.", def: "The term is derived from the Roman law, and means a person holding the character of a trustee, or a character analogous to that of a trustee, in respect to the trust and confidence involved in it and the scrupulous good faith and candor which it requires." },
  { word: "FORCE MAJEURE", pos: "Fr.", def: "Superior or irresistible force; an event that can neither be anticipated nor controlled, excusing performance of a contractual duty." },
  { word: "GARNISHMENT", pos: "n.", def: "A species of attachment for reaching any property or credits of a debtor which are in the hands of a third person." },
  { word: "GOOD FAITH", pos: "n.", def: "An honest intention to abstain from taking any unconscientious advantage of another, even through the forms or technicalities of law, together with an absence of all information or belief of facts which would render the transaction unconscientious." },
  { word: "HABEAS CORPUS", pos: "Lat.", def: "You have the body. The name given to a variety of writs, having for their object to bring a party before a court or judge, most commonly to secure the party's release from unlawful custody." },
  { word: "IN CAMERA", pos: "Lat.", def: "In chambers; in private. A cause is said to be heard in camera either when the hearing is had before the judge in his private chambers or when all spectators are excluded from the courtroom." },
  { word: "INDEMNITY", pos: "n.", def: "A collateral contract or assurance, by which one person engages to secure another against an anticipated loss, or to prevent him from being damnified by the legal consequences of an act or forbearance." },
  { word: "INJUNCTION", pos: "n.", def: "A prohibitive writ issued by a court of equity, at the suit of a party complainant, directed to a party defendant, forbidding the latter from doing some act which he is threatening or attempting to commit." },
  { word: "JOINT TENANCY", pos: "n.", def: "An estate in joint tenancy is an estate in fee, for life, for years, or at will, arising by purchase or grant to two or more persons, and characterized by the right of survivorship." },
  { word: "JURISDICTION", pos: "n.", def: "The authority by which courts and judicial officers take cognizance of and decide cases; power to hear and determine a cause; power to render the particular judgment in a particular case." },
  { word: "LARCENY", pos: "n.", def: "The wrongful and fraudulent taking and carrying away, by one person, of the mere personal goods of another, from any place, with a felonious intent to convert them to his own use, and make them his own property, without the consent of the owner." },
  { word: "LIEN", pos: "n.", def: "A hold or claim which one person has upon the property of another, as a security for some debt or charge." },
  { word: "LITIGATION", pos: "n.", def: "A judicial controversy; a contest in a court of justice for the purpose of enforcing a right." },
  { word: "MALICE AFORETHOUGHT", pos: "n.", def: "A predetermination to commit an act injurious to another, without legal justification or excuse; a design formed to do mischief antecedent to the act done." },
  { word: "MANDAMUS", pos: "n.", def: "We command. This is the name of a writ formerly issued by the king, and now by the sovereign people, commanding an officer, corporation, inferior court, or other person to perform a specified act." },
  { word: "NEGLIGENCE", pos: "n.", def: "The omission to do something which a reasonable man, guided by those ordinary considerations which ordinarily regulate human affairs, would do, or the doing of something which a reasonable and prudent man would not do." },
  { word: "NULL AND VOID", pos: "n.", def: "Having no legal force or binding effect; unable, either in law or equity, to confer any right or to be the foundation of any legal proceedings." },
  { word: "PERJURY", pos: "n.", def: "In criminal law, the willful assertion as to a matter of fact, opinion, belief, or knowledge, made by a witness in a judicial proceeding as part of his evidence, either upon oath or in any form allowed by law to be substituted for an oath, whether such evidence is given in open court, or in an affidavit, or otherwise, such assertion being known to such witness to be false." },
  { word: "PLAINTIFF", pos: "n.", def: "A person who brings an action; the party who complains or sues in a personal action and is so named on the record." },
  { word: "QUANTUM MERUIT", pos: "Lat.", def: "As much as he has deserved. The common count in an action of assumpsit for work and labor, founded on an implied promise on the part of defendant to pay the plaintiff as much as he reasonably deserved." },
  { word: "QUID PRO QUO", pos: "Lat.", def: "What for what; something for something. Used to denote consideration in the law of contracts." },
  { word: "RES JUDICATA", pos: "Lat.", def: "A thing adjudicated; an issue that has been definitively settled by judicial decision; a matter finally decided on its merits by a court of competent jurisdiction." },
  { word: "STARE DECISIS", pos: "Lat.", def: "To abide by, or adhere to, decided cases. Policy of courts to stand by precedent and not to disturb settled points." },
  { word: "SUBPOENA", pos: "n.", def: "A process to cause a witness to appear and give testimony before a court or magistrate, commanding the person to whom it is directed to attend and testify, under a penalty." },
  { word: "TORT", pos: "n.", def: "A private or civil wrong or injury, other than breach of contract, for which the court will provide a remedy in the form of an action for damages." },
  { word: "ULTRA VIRES", pos: "Lat.", def: "Beyond the powers. This phrase is chiefly used to indicate an act of a corporation which is beyond the powers conferred upon it by its charter, or the statutes under which it was instituted." },
  { word: "WARRANTY", pos: "n.", def: "In the law of sales, an engagement by the seller of property that the goods or property sold are as represented or promised, or that they are free from defects." },
  { word: "ACCESSORY", pos: "n.", def: "In criminal law, one who is not the chief actor in the offense, nor present at its performance, but is some way concerned therein, either before or after the act committed." },
  { word: "ADJUDICATION", pos: "n.", def: "The determination of a controversy and a pronouncement of judgment upon the matter in dispute; the giving or pronouncing a judgment or decree in a cause." },
  { word: "AMICUS CURIAE", pos: "Lat.", def: "A friend of the court. A person who has no right to appear in a suit, but is allowed to introduce evidence or argument to protect his own interests, or one who volunteers information on a point of law in which the judge is doubtful or mistaken." },
  { word: "APPEAL", pos: "n.", def: "The complaint to a superior court of an injustice done by an inferior one; the removal of a cause from a court of inferior to one of superior jurisdiction, for the purpose of obtaining a review and retrial." },
  { word: "ARBITRATION", pos: "n.", def: "The investigation and determination of a matter or matters of difference between contending parties, by one or more unofficial persons, chosen by the parties, called arbitrators." },
  { word: "ASSAULT", pos: "n.", def: "An attempt or offer to beat another, without touching him; as if one lifts up his cane, or his fist, in a threatening manner at another." },
  { word: "ATTACHMENT", pos: "n.", def: "The act or process of taking, apprehending, or seizing persons or property, by virtue of a writ, summons, or other judicial order, and bringing the same into the custody of the law." },
  { word: "BENEFICIARY", pos: "n.", def: "He for whose benefit a trust is created; the person entitled to the benefit of a trust; the cestui que trust." },
  { word: "BEQUEST", pos: "n.", def: "A gift by will of personal property; a legacy." },
  { word: "BREACH OF THE PEACE", pos: "n.", def: "A violation of the public tranquillity and order; the offense of breaking or disturbing the public peace by any riotous, forcible, or unlawful proceeding." },
  { word: "BURDEN OF PROOF", pos: "n.", def: "In the law of evidence, the necessity or duty of affirmatively proving a fact or facts in dispute on an issue raised between the parties in a cause." },
  { word: "CHATTEL", pos: "n.", def: "An article of personal property; any species of property not amounting to a freehold or fee in land." },
  { word: "CIRCUMSTANTIAL EVIDENCE", pos: "n.", def: "Evidence directed to the attending circumstances of a particular fact or event, from which the existence or non-existence of that fact may be inferred as a logical result." },
  { word: "CODICIL", pos: "n.", def: "A supplement or an addition to a will; it may add to, subtract from, alter, restrain, or entirely revoke the provisions of the will." },
  { word: "COLLUSION", pos: "n.", def: "An agreement between two or more persons to defraud a person of his rights, or to obtain an object forbidden by law." },
  { word: "COMMON LAW", pos: "n.", def: "As distinguished from law created by the enactment of legislatures, the common law comprises the body of those principles and rules of action, relating to the government and security of persons and property, which derive their authority solely from usages and customs, or from the judgments and decrees of the courts." },
  { word: "CONSPIRACY", pos: "n.", def: "In criminal law, a combination or confederacy between two or more persons formed for the purpose of committing, by their joint efforts, some unlawful or criminal act." },
  { word: "CONTEMPT OF COURT", pos: "n.", def: "A disregard of, or disobedience to, the rules or orders of a judicial body, or interruption of its proceedings by disorderly behavior or insolent language, in its presence or so near thereto as to disturb the proceedings or impair the respect due to such a body." },
  { word: "COVENANT", pos: "n.", def: "An agreement, convention, or promise of two or more parties, by deed in writing, signed, and delivered, by which either of the parties pledges himself to the other that something is either done or shall be done." },
  { word: "CREDITOR", pos: "n.", def: "One who has a right to require the fulfillment of an obligation or contract; one to whom a sum of money or other thing is due, by certain and express agreement." },
  { word: "DEFENDANT", pos: "n.", def: "The party against whom relief or recovery is sought in an action or suit, or the accused party in a criminal case." },
  { word: "DEPOSITION", pos: "n.", def: "The testimony of a witness taken upon oral question or written interrogatories, not in open court, but reduced to writing and duly authenticated, and intended to be used in preparation and upon the trial of a civil or criminal cause." },
  { word: "DEVISE", pos: "n.", def: "A testamentary disposition of land or realty; a gift of real property by the last will and testament of the donor." },
  { word: "DISCOVERY", pos: "n.", def: "The disclosure by a party of facts, deeds, documents, or other things which are exclusively within his own knowledge or possession, and which are necessary to the party seeking discovery as a part of his case." },
  { word: "DOMICILE", pos: "n.", def: "That place where a man has his true, fixed, and permanent home and principal establishment, and to which, whenever he is absent, he has the intention of returning." },
  { word: "DURESS", pos: "n.", def: "Unlawful constraint exercised upon a man whereby he is forced to do some act against his will." },
  { word: "EMINENT DOMAIN", pos: "n.", def: "The right of the state, through its regular organization, to reassert, either temporarily or permanently, its dominion over any portion of the soil of the state on account of public exigency and for the public good." },
  { word: "ENCUMBRANCE", pos: "n.", def: "A burden upon land, depreciative of its value, such as a lien, easement, servitude, or right of way." },
  { word: "EQUITABLE ESTOPPEL", pos: "n.", def: "The doctrine by which a person may be precluded by his own act or conduct, or silence when it was his duty to speak, from asserting a right which he otherwise would have had." },
  { word: "EVICTION", pos: "n.", def: "Dispossession by process of law; the act of depriving a person of the possession of land or rental property, in pursuance of the judgment of a court." },
  { word: "EXECUTOR", pos: "n.", def: "A person appointed by a testator to carry out the directions and requests in his will, and to dispose of the property according to his testamentary provisions after his decease." },
  { word: "EXTRADITION", pos: "n.", def: "The surrender by one nation to another of an individual accused or convicted of an offense outside of its own territory and within the territorial jurisdiction of the other, which, being competent to try and to punish him, demands the surrender." },
  { word: "FEE SIMPLE", pos: "n.", def: "A fee simple is an estate limited absolutely to a man and his heirs and assigns forever without limitation or condition; it is the largest estate and most extensive interest that can be enjoyed in land." },
  { word: "FORECLOSURE", pos: "n.", def: "A proceeding, either strictly judicial or partaking more or less of a judicial character, appropriate to the ascertainment and payment of the whole amount due upon the mortgage, and to the sale of the mortgaged premises in satisfaction of that amount." },
  { word: "FRAUD", pos: "n.", def: "An intentional perversion of truth for the purpose of inducing another in reliance upon it to part with some valuable thing belonging to him or to surrender a legal right." },
  { word: "GRAND JURY", pos: "n.", def: "A body of men, selected and summoned by a court to inquire into crimes committed or triable within a county, and to accuse and indict persons of such crimes when there is sufficient evidence to warrant holding them for trial." },
  { word: "GUARDIAN", pos: "n.", def: "A person lawfully invested with the power, and charged with the duty, of taking care of the person and managing the property and rights of another person, who, for defect of age, understanding, or self-control, is considered incapable of administering his own affairs." },
  { word: "HEARSAY EVIDENCE", pos: "n.", def: "Testimony given by a witness who relates not what he knows personally, but what others have told him, or what he has heard said by others." },
  { word: "HOMICIDE", pos: "n.", def: "The killing of any human creature. It is either without fault, as in the case of the execution of a criminal by due course of law, or felonious, as murder or manslaughter." },
  { word: "IMMUNITY", pos: "n.", def: "Exemption from performing duties which the law generally requires other citizens to perform; freedom from prosecution or liability." },
  { word: "INCUMBENT", pos: "n.", def: "The person who is in present possession of an office; one who is legally authorized to discharge the duties of an office." },
  { word: "INDICTMENT", pos: "n.", def: "An accusation in writing found and presented by a grand jury, legally convoked and sworn, to the court in which it is impaneled, charging that a person therein named has done some act, or been guilty of some omission, which, by law, is a public offense." },
  { word: "INFRINGEMENT", pos: "n.", def: "A breaking into, or trespass upon; a violation or transgression, as of a right or law; used chiefly of the invasion of rights secured by patent, copyright, or trademark." },
  { word: "INSOLVENCY", pos: "n.", def: "The condition of a person who is insolvent; inability to pay one's debts; lack of means to pay one's debts." },
  { word: "INTESTATE", pos: "a.", def: "A person who dies without leaving a will, or leaves one which is defective in form, or which fails to appoint an executor, is said to die intestate." },
  { word: "LEASE", pos: "n.", def: "A species of contract for the possession and profits of lands and tenements, either for life, or for a certain term of years, or during the pleasure of the parties." },
  { word: "LEGACY", pos: "n.", def: "A gift or bequest of personal property by last will and testament." },
  { word: "LIBEL", pos: "n.", def: "A malicious defamation, expressed either in printing or writing, or by signs or pictures, tending to injure the reputation of another, exposing him to public hatred, contempt, or ridicule." },
  { word: "LIQUIDATED DAMAGES", pos: "n.", def: "Damages the amount of which has been determined or agreed upon by the parties, at the time of entering into a contract, as compensation for a breach thereof." },
  { word: "MALFEASANCE", pos: "n.", def: "The doing of an act which a person ought not to do at all, or which is positively unlawful; the commission of some act which is positively prohibited by law." },
  { word: "MANDATORY INJUNCTION", pos: "n.", def: "A species of injunction requiring the person against whom it is directed to perform a positive act, as distinguished from a prohibitive injunction, which forbids him to do an act." },
  { word: "MISDEMEANOR", pos: "n.", def: "Offenses less than felonies; a general name for crimes and offenses inferior to felonies, and generally punishable by fine, or imprisonment otherwise than in a penitentiary." },
  { word: "MORTGAGE", pos: "n.", def: "An estate created by a conveyance absolute in its form, but intended to secure the performance of some act, such as the payment of money, and to become void if the act is performed." },
  { word: "NOTARY PUBLIC", pos: "n.", def: "A public officer whose function it is to attest and certify, by his hand and official seal, certain classes of documents, in order to give them credit and authenticity in foreign jurisdictions." },
  { word: "NUISANCE", pos: "n.", def: "Anything that unlawfully worketh hurt, inconvenience, or damage to another, or which is offensive to the senses, and which violates the laws of decency, or obstructs the reasonable and comfortable use of property." },
  { word: "OATH", pos: "n.", def: "An outward pledge given by the person taking it that his attestation or promise is made under an immediate sense of his responsibility to God." },
  { word: "PAROLE EVIDENCE", pos: "n.", def: "Oral or verbal evidence; that which is given by word of mouth; the ordinary kind of evidence given by witnesses in court." },
  { word: "PATENT", pos: "n.", def: "The instrument by which a grant of some privilege, property, or authority is made by the government to a person or persons; commonly used of a grant securing to an inventor the exclusive right to make, use, and sell his invention for a term of years." },
  { word: "PLEA", pos: "n.", def: "In common law pleading, the answer which the defendant in an action at law makes to the plaintiff's declaration, and in which he sets up matter of fact as defense." },
  { word: "PRECEDENT", pos: "n.", def: "An adjudged case or decision of a court of justice, considered as furnishing an example or authority for an identical or similar case afterwards arising, or a similar question of law." },
  { word: "PROBATE", pos: "n.", def: "The act or process of proving a will; the proof before an officer authorized by law that a document produced before him for official recognition and registration is the last will and testament of the deceased person." },
  { word: "QUASH", pos: "v.", def: "To overthrow; to abate, annul, void, or completely do away with, as to quash an indictment." },
  { word: "QUORUM", pos: "n.", def: "Such a number of the members of a body as is competent by law or by usage to transact business." },
  { word: "RATIFICATION", pos: "n.", def: "The confirmation of a previous act done either by the party himself or by another; the adoption of an act performed by another, without previous authorization." },
  { word: "RECEIVER", pos: "n.", def: "An indifferent person between the parties to a cause, appointed by the court to receive and preserve the property or fund in litigation, pendente lite, when it does not seem reasonable that either party should hold possession." },
  { word: "RECIDIVIST", pos: "n.", def: "One who has been previously convicted of a crime, and who, on a later occasion, commits another." },
  { word: "REPLEVIN", pos: "n.", def: "A form of action which lies to recover the possession of personal chattels, where the claimant alleges that they have been taken from him unlawfully." },
  { word: "RESCISSION", pos: "n.", def: "The abrogation, annulling, or unmaking of a contract, and the placing of the parties to it in status quo." },
  { word: "RETAINER", pos: "n.", def: "The act of a client in employing his attorney or counsel, and also, generally, the fee which the client pays when he retains the attorney to act for him." },
  { word: "SEARCH WARRANT", pos: "n.", def: "An order in writing, issued by a justice or other magistrate, in the name of the state, directed to a sheriff, constable, or other officer, authorizing him to search a specified house or other premises for stolen goods or other articles." },
  { word: "SEQUESTRATION", pos: "n.", def: "The act of taking property or estate out of the possession of its owner pending a suit or dispute, and putting it in the possession of an indifferent person." },
  { word: "SLANDER", pos: "n.", def: "The speaking of base and defamatory words tending to prejudice another in his reputation, community standing, office, trade, business, or means of livelihood." },
  { word: "STATUTE OF FRAUDS", pos: "n.", def: "The name commonly given to a very celebrated English statute, passed in the reign of Charles II, requiring certain classes of contracts to be in writing, signed by the party to be charged, in order to be enforceable." },
  { word: "STATUTE OF LIMITATIONS", pos: "n.", def: "A statute prescribing limitations to the right of action on certain described causes of action or criminal prosecutions; that is, declaring that no suit shall be maintained on such causes of action unless brought within a specified period of time after the right accrued." },
  { word: "SUBROGATION", pos: "n.", def: "The substitution of one person in the place of another with reference to a lawful claim, demand, or right, so that he who is substituted succeeds to the rights of the other in relation to the debt or claim." },
  { word: "SUMMONS", pos: "n.", def: "A writ, directed to the sheriff or other proper officer, requiring him to notify the person named that an action has been commenced against him in the court from which the writ issues, and that he is required to appear, on a day named, and answer the complaint." },
  { word: "TESTAMENT", pos: "n.", def: "A will; the disposition of one's personal property, to take effect after death; a legal declaration of a man's intentions as to the disposal of his estate after his death." },
  { word: "TESTIMONY", pos: "n.", def: "Evidence given by a competent witness, under oath or affirmation, as distinguished from evidence derived from writings and other sources." },
  { word: "TRESPASS", pos: "n.", def: "An unlawful interference with one's person, property, or rights; at common law, a form of action for the recovery of damages for any injury committed with direct and immediate force or violence." },
  { word: "TRUSTEE", pos: "n.", def: "The person appointed, or required by law, to execute a trust; one in whom an estate, interest, or power is vested, under an express or implied agreement to administer or dispose of it for the benefit or to the use of another." },
  { word: "UNJUST ENRICHMENT", pos: "n.", def: "The retention of a benefit conferred by another, without offering compensation, in circumstances where compensation is reasonably expected; a doctrine that requires restitution to prevent one party from unfairly profiting at another's expense." },
  { word: "USURY", pos: "n.", def: "Unlawful contract upon the loan of money, to receive the same again with exorbitant increase; the taking of more interest for the use of money than the law allows." },
  { word: "VENUE", pos: "n.", def: "The particular county, city, or geographical area in which a court with jurisdiction may hear and determine a case." },
  { word: "VERDICT", pos: "n.", def: "The formal and unanimous decision or finding of a jury, impaneled and sworn for the trial of a cause, upon the matters or questions duly submitted to them upon the trial." },
  { word: "VOID", pos: "a.", def: "Null; ineffectual; nugatory; having no legal force or binding effect; unable, in law, to support the purpose for which it was intended." },
  { word: "VOIDABLE", pos: "a.", def: "That may be avoided, or declared void; not absolutely void, but capable of being adjudged void at the instance of the party who has the right." },
  { word: "WAIVER", pos: "n.", def: "The voluntary relinquishment or abandonment, express or implied, of a legal right or advantage." },
  { word: "WITNESS", pos: "n.", def: "One who testifies to what he has seen, heard, or otherwise observed; one who gives evidence, oral or written, in a cause before a court." },
  { word: "WRIT", pos: "n.", def: "An order or mandatory process in writing, issued in the name of the sovereign or of a court or judicial officer, commanding the person to whom it is directed to perform or refrain from performing some specified act." },
];
