/* ================================================================
   Uniform Commercial Code (UCC) — Core Sections
   ----------------------------------------------------------------
   The UCC's enacted statutory text is public domain (it's law,
   adopted by state legislatures — U.S. government-edict works
   are not copyrightable). Only the ALI/ULC's official commentary
   and third-party sites' own markup/annotations are copyrighted.

   This is a curated reference to the most commonly cited sections
   across the articles most people look up: Article 1 (General
   Provisions), Article 2 (Sales), Article 3 (Negotiable
   Instruments), and Article 9 (Secured Transactions). Numbering
   follows the standard UCC section format (e.g. § 2-105); a few
   states vary slightly in their own enactments.
   ================================================================ */

const UCC_SECTIONS = [
  // ---------------- ARTICLE 1: GENERAL PROVISIONS ----------------
  { code: "§ 1-103", article: "1", title: "Construction of Code to Promote Its Purposes and Policies", def: "The Code is to be liberally construed to promote its underlying purposes: simplifying and modernizing the law of commercial transactions, permitting the continued expansion of commercial practices through custom and agreement, and making commercial law uniform among the states." },
  { code: "§ 1-201", article: "1", title: "General Definitions", def: "Defines core terms used throughout the Code, including 'agreement,' 'good faith' (honesty in fact and the observance of reasonable commercial standards of fair dealing), 'party,' 'purchaser,' 'security interest,' and 'value.'" },
  { code: "§ 1-201(b)(20)", article: "1", title: "'Good Faith'", def: "Good faith means honesty in fact and the observance of reasonable commercial standards of fair dealing." },
  { code: "§ 1-202", article: "1", title: "Notice; Knowledge", def: "A person has 'notice' of a fact when they have actual knowledge of it, receive a notification of it, or have reason to know it exists from other facts known to them at the time." },
  { code: "§ 1-203", article: "1", title: "Lease Distinguished from Security Interest", def: "Establishes the test for whether a transaction described as a lease actually creates a security interest, based on whether the lessee cannot terminate and the lessor's interest is nominal." },
  { code: "§ 1-204", article: "1", title: "Value", def: "A person gives value for rights if they acquire them in exchange for a binding commitment to extend credit, as security for or in satisfaction of a preexisting claim, by accepting delivery under a preexisting contract, or in exchange for other value." },
  { code: "§ 1-205", article: "1", title: "Reasonable Time; Seasonableness", def: "Whether a time for taking action is reasonable depends on the nature, purpose, and circumstances of the action. An action is taken 'seasonably' if it is taken at or within the agreed time, or if none, within a reasonable time." },
  { code: "§ 1-302", article: "1", title: "Variation by Agreement", def: "Most provisions of the Code may be varied by agreement between the parties, except that the obligations of good faith, diligence, reasonableness, and care cannot be disclaimed by agreement, though the parties may set reasonable standards for measuring them." },
  { code: "§ 1-303", article: "1", title: "Course of Performance, Course of Dealing, and Usage of Trade", def: "Establishes how prior conduct between parties (course of performance, course of dealing) and industry custom (usage of trade) are used to interpret and supplement the express terms of an agreement." },
  { code: "§ 1-304", article: "1", title: "Obligation of Good Faith", def: "Every contract or duty within the Code imposes an obligation of good faith in its performance and enforcement." },
  { code: "§ 1-308", article: "1", title: "Performance or Acceptance Under Reservation of Rights", def: "A party who, with explicit reservation of rights, performs or promises performance or assents to performance in a manner demanded by the other party does not thereby prejudice the rights reserved." },

  // ---------------- ARTICLE 2: SALES ----------------
  { code: "§ 2-102", article: "2", title: "Scope; Certain Security and Other Transactions Excluded from This Article", def: "Article 2 applies to transactions in goods; it does not apply to any transaction which, although in the form of an unconditional contract to sell or present sale, is intended to operate only as a security transaction." },
  { code: "§ 2-104", article: "2", title: "'Merchant'; 'Between Merchants'", def: "A merchant is a person who deals in goods of the kind involved in the transaction, or who by occupation holds themself out as having knowledge or skill peculiar to the practices or goods involved." },
  { code: "§ 2-105", article: "2", title: "'Goods'; 'Future' Goods; 'Lot'; 'Commercial Unit'", def: "'Goods' means all things that are movable at the time of identification to the contract for sale, other than money, investment securities, and things in action." },
  { code: "§ 2-106", article: "2", title: "'Contract'; 'Agreement'; 'Contract for Sale'; 'Sale'; 'Present Sale'", def: "A 'sale' consists in the passing of title from the seller to the buyer for a price. A 'present sale' means a sale which is accomplished by the making of the contract." },
  { code: "§ 2-201", article: "2", title: "Formal Requirements: Statute of Frauds", def: "A contract for the sale of goods for the price of $500 or more is not enforceable unless there is a writing sufficient to indicate that a contract for sale has been made and signed by the party against whom enforcement is sought." },
  { code: "§ 2-206", article: "2", title: "Offer and Acceptance in Formation of Contract", def: "Unless otherwise unambiguously indicated by the language or circumstances, an offer to make a contract shall be construed as inviting acceptance in any manner and by any medium reasonable in the circumstances." },
  { code: "§ 2-207", article: "2", title: "Additional Terms in Acceptance or Confirmation", def: "A definite and seasonable expression of acceptance operates as an acceptance even though it states terms additional to or different from those offered, unless acceptance is expressly made conditional on assent to the additional or different terms — the so-called 'battle of the forms' provision." },
  { code: "§ 2-209", article: "2", title: "Modification, Rescission, and Waiver", def: "An agreement modifying a contract within this Article needs no consideration to be binding. A signed agreement which excludes modification or rescission except by a signed writing generally cannot otherwise be modified or rescinded." },
  { code: "§ 2-302", article: "2", title: "Unconscionable Contract or Clause", def: "If a court finds a contract or any clause was unconscionable at the time it was made, the court may refuse to enforce the contract, enforce the remainder without the unconscionable clause, or limit the clause's application to avoid an unconscionable result." },
  { code: "§ 2-314", article: "2", title: "Implied Warranty: Merchantability; Usage of Trade", def: "Unless excluded or modified, a warranty that the goods shall be merchantable is implied in a contract for their sale if the seller is a merchant with respect to goods of that kind." },
  { code: "§ 2-315", article: "2", title: "Implied Warranty: Fitness for Particular Purpose", def: "Where the seller at the time of contracting has reason to know any particular purpose for which the goods are required, and that the buyer is relying on the seller's skill or judgment to select suitable goods, there is an implied warranty that the goods shall be fit for that purpose." },
  { code: "§ 2-316", article: "2", title: "Exclusion or Modification of Warranties", def: "Sets out the rules for how express and implied warranties can be excluded or modified, including that language to exclude the implied warranty of merchantability must mention 'merchantability' and, if in writing, must be conspicuous." },
  { code: "§ 2-401", article: "2", title: "Passing of Title; Reservation for Security; Limited Application of This Section", def: "Title to goods passes from the seller to the buyer in any manner and on any conditions explicitly agreed on by the parties." },
  { code: "§ 2-501", article: "2", title: "Insurable Interest in Goods; Manner of Identification of Goods", def: "The buyer obtains a special property and an insurable interest in goods by identification of existing goods as goods to which the contract refers, even though the goods so identified are non-conforming and the buyer has an option to return or reject them." },
  { code: "§ 2-509", article: "2", title: "Risk of Loss in the Absence of Breach", def: "Governs when the risk of loss passes from seller to buyer depending on whether the seller is required to ship by carrier, deliver at a particular destination, or whether goods are held by a bailee." },
  { code: "§ 2-601", article: "2", title: "Buyer's Rights on Improper Delivery", def: "If the goods or the tender of delivery fail in any respect to conform to the contract, the buyer may reject the whole, accept the whole, or accept any commercial unit and reject the rest — the 'perfect tender rule.'" },
  { code: "§ 2-608", article: "2", title: "Revocation of Acceptance in Whole or in Part", def: "A buyer may revoke acceptance of a lot or commercial unit whose non-conformity substantially impairs its value if they accepted it on the reasonable assumption its non-conformity would be cured, or without discovering the non-conformity if acceptance was reasonably induced by the difficulty of discovery or by the seller's assurances." },
  { code: "§ 2-702", article: "2", title: "Seller's Remedies on Discovery of Buyer's Insolvency", def: "Where the seller discovers the buyer is insolvent, the seller may refuse delivery except for cash, and may reclaim goods delivered on credit if a demand is made within a reasonable time after the buyer's receipt of the goods." },
  { code: "§ 2-703", article: "2", title: "Seller's Remedies in General", def: "Where the buyer wrongfully rejects or revokes acceptance of goods, or fails to make a payment due, the aggrieved seller may withhold delivery, stop delivery by a bailee, resell and recover damages, recover damages for non-acceptance, or cancel." },
  { code: "§ 2-711", article: "2", title: "Buyer's Remedies in General", def: "Where the seller fails to make delivery or repudiates, or the buyer rightfully rejects or justifiably revokes acceptance, the buyer may cancel and recover the price paid, and in addition may cover and recover damages, or recover damages for non-delivery." },
  { code: "§ 2-712", article: "2", title: "'Cover'; Buyer's Procurement of Substitute Goods", def: "After a breach, the buyer may 'cover' by making, in good faith and without unreasonable delay, any reasonable purchase of or contract to purchase goods in substitution for those due from the seller, and recover the difference between the cost of cover and the contract price." },

  // ---------------- ARTICLE 3: NEGOTIABLE INSTRUMENTS ----------------
  { code: "§ 3-104", article: "3", title: "Negotiable Instrument", def: "An unconditional promise or order to pay a fixed amount of money, with or without interest, payable to bearer or to order, on demand or at a definite time, without other undertakings not authorized by this Article." },
  { code: "§ 3-201", article: "3", title: "Negotiation", def: "Negotiation is a transfer of possession of an instrument, whether voluntary or involuntary, by a person other than the issuer to a person who thereby becomes its holder." },
  { code: "§ 3-302", article: "3", title: "Holder in Due Course", def: "A holder in due course is one who takes an instrument for value, in good faith, and without notice that it is overdue, has been dishonored, contains an unauthorized signature, or is subject to a claim or defense." },
  { code: "§ 3-305", article: "3", title: "Defenses and Claims in Recoupment", def: "Sets out which defenses (such as fraud in the factum, forgery, or discharge in insolvency) may be asserted against a holder in due course, and which ordinary defenses (such as breach of contract) may not." },
  { code: "§ 3-401", article: "3", title: "Signature", def: "A person is not liable on an instrument unless the person signed it, or it was signed by an authorized representative." },
  { code: "§ 3-407", article: "3", title: "Alteration", def: "Alteration means an unauthorized change in an instrument that purports to modify the obligation of a party, or an unauthorized addition of words or numbers to an incomplete instrument. Discusses the effect on the obligations of parties." },

  // ---------------- ARTICLE 9: SECURED TRANSACTIONS ----------------
  { code: "§ 9-102", article: "9", title: "Definitions and Index of Definitions", def: "Provides the master list of definitions used throughout Article 9, including 'collateral,' 'debtor,' 'secured party,' 'security agreement,' and 'proceeds.'" },
  { code: "§ 9-109", article: "9", title: "Scope", def: "Article 9 applies to any transaction, regardless of its form, that creates a security interest in personal property or fixtures by contract, including sales of accounts, chattel paper, and payment intangibles." },
  { code: "§ 9-102(a)(28)", article: "9", title: "'Debtor'", def: "A person having an interest, other than a security interest or other lien, in the collateral, whether or not the person is an obligor." },
  { code: "§ 9-102(a)(73)", article: "9", title: "'Secured Party'", def: "A person in whose favor a security interest is created or provided for under a security agreement, whether or not any obligation to be secured is outstanding." },
  { code: "§ 9-203", article: "9", title: "Attachment and Enforceability of Security Interest; Proceeds; Supporting Obligations; Formal Requisites", def: "A security interest attaches to collateral, and becomes enforceable, when value has been given, the debtor has rights in the collateral, and the debtor has authenticated a security agreement describing the collateral (unless the secured party has possession or control)." },
  { code: "§ 9-301", article: "9", title: "Law Governing Perfection and Priority of Security Interests", def: "Generally, the law of the jurisdiction where the debtor is located governs perfection, the effect of perfection or non-perfection, and the priority of a security interest in collateral." },
  { code: "§ 9-308", article: "9", title: "When Security Interest or Agricultural Lien Is Perfected; Continuity of Perfection", def: "A security interest is perfected when it has attached and all applicable requirements for perfection (such as filing a financing statement) have been satisfied." },
  { code: "§ 9-310", article: "9", title: "When Filing Required to Perfect Security Interest or Agricultural Lien; Security Interests and Agricultural Liens to Which Filing Provisions Do Not Apply", def: "Sets out when a financing statement must be filed to perfect a security interest, and lists the categories of security interests (such as those perfected by possession or automatically) for which filing is not required." },
  { code: "§ 9-322", article: "9", title: "Priorities Among Conflicting Security Interests in and Agricultural Liens on Same Collateral", def: "Establishes the 'first to file or perfect' rule: conflicting perfected security interests in the same collateral rank according to priority in time of filing or perfection." },
  { code: "§ 9-324", article: "9", title: "Priority of Purchase-Money Security Interests", def: "A perfected purchase-money security interest in goods (other than inventory or livestock) has priority over a conflicting security interest in the same goods if it is perfected at the time the debtor receives possession or within 20 days thereafter." },
  { code: "§ 9-609", article: "9", title: "Secured Party's Right to Take Possession After Default", def: "After default, a secured party may take possession of collateral without judicial process if this can be done without breach of the peace, or may proceed by judicial process." },
  { code: "§ 9-610", article: "9", title: "Disposition of Collateral After Default", def: "After default, a secured party may sell, lease, license, or otherwise dispose of collateral in its present condition or following any commercially reasonable preparation or processing." },
];
